class AppConstants {
  static const Map<String, List<String>> categorizedSkills = {
    "Accounting, Finance & Banking": [
      "Senior Accountant",
      "Junior Accountant",
      "Cost Accountant",
      "Management Accountant",
      "Financial Analyst",
      "External Auditor",
      "Internal Auditor",
      "Tax Consultant",
      "IFRS Specialist",
      "Peachtree/Sage Accounting",
      "QuickBooks Specialist",
      "Bank Manager",
      "Loan/Credit Officer",
      "Bank Teller",
      "Customer Service Manager (Banking)",
      "Insurance Underwriter",
      "Claims Officer",
      "Investment Analyst",
      "Grant Accountant",
      "Treasury Management",
      "Cashier",
      "Fixed Assets Controller",
      "Inventory Accountant"
    ],
    "Information Technology & Computer Science": [
      "Full Stack Developer",
      "Frontend Developer (React/Vue/Angular)",
      "Backend Developer (Node/Python/Java)",
      "Mobile App Developer (Flutter/React Native/Native Android/iOS)",
      "UI/UX Designer",
      "Graphics Designer",
      "Motion Graphics Artist",
      "Video Editor",
      "Cybersecurity Analyst",
      "Ethical Hacker",
      "Network Engineer",
      "System Administrator",
      "Database Administrator (MySQL/PostgreSQL/Oracle)",
      "Cloud Engineer (AWS/Azure/Google Cloud)",
      "Data Scientist",
      "Machine Learning Engineer",
      "IT Support Technician",
      "Hardware Maintenance & Repair",
      "Software Quality Assurance (QA) Tester",
      "DevOps Engineer",
      "Blockchain Developer",
      "GIS & Remote Sensing Specialist"
    ],
    "Engineering & Construction": [
      "Civil Engineer",
      "Site Engineer",
      "Office Engineer",
      "Structural Engineer",
      "Architect",
      "Urban Planner",
      "Interior Designer",
      "Quantity Surveyor",
      "Electrical Engineer",
      "Electronics Engineer",
      "Power Systems Engineer",
      "Mechanical Engineer",
      "Automotive Engineer",
      "Sanitary Engineer",
      "Geotechnical Engineer",
      "Hydraulic Engineer",
      "Project Coordinator (Construction)",
      "Surveyor",
      "Draftsperson (AutoCAD/Revit/ArchiCAD)",
      "Road & Highway Engineer",
      "Water Resource Engineer",
      "Construction Foreman"
    ],
    "Healthcare & Medical Services": [
      "General Practitioner (GP)",
      "Specialist Doctor (Surgeon/Pediatrician/etc.)",
      "Medical Intern",
      "Health Officer",
      "Clinical Nurse",
      "Surgical Nurse",
      "Midwifery Professional",
      "Medical Laboratory Technologist",
      "Pharmacist",
      "Druggist",
      "Radiology Technician",
      "Anesthetist",
      "Physiotherapist",
      "Dentist",
      "Optometrist",
      "Psychiatrist",
      "Clinical Psychologist",
      "Nutritionist/Dietitian",
      "Emergency Medical Technician (EMT)",
      "Public Health Specialist",
      "Epidemiologist",
      "Medical Records Officer"
    ],
    "Management, Administration & HR": [
      "Human Resource (HR) Manager",
      "HR Officer",
      "General Manager",
      "Operations Manager",
      "Project Manager",
      "Project Coordinator",
      "Administrative Assistant",
      "Executive Secretary",
      "Office Manager",
      "Record Management Officer",
      "Logistics Manager",
      "Supply Chain Officer",
      "Procurement & Purchasing Specialist",
      "Storekeeper",
      "Property Management Officer",
      "Fleet Manager",
      "Event Organizer",
      "Business Development Manager"
    ],
    "Marketing, Sales & Communication": [
      "Sales Manager",
      "Sales Representative",
      "Marketing Specialist",
      "Digital Marketer",
      "Social Media Manager",
      "Content Creator/Influencer",
      "Public Relations (PR) Officer",
      "Brand Manager",
      "Market Researcher",
      "Copywriter",
      "Telemarketer",
      "Customer Support Specialist",
      "Call Center Agent",
      "Graphic Illustrator",
      "Advertising Manager",
      "Media Production Specialist"
    ],
    "NGO, Social Science & Research": [
      "Monitoring & Evaluation (M&E) Officer",
      "Program Officer",
      "Grant Writer",
      "Livelihood Specialist",
      "Gender/Women's Affairs Officer",
      "Child Protection Officer",
      "Community Development Worker",
      "Sociologist",
      "Social Worker",
      "Anthropologist",
      "Economist",
      "Statistician",
      "Data Collector",
      "Research Assistant",
      "Peacebuilding & Conflict Resolution Specialist",
      "Human Rights Activist"
    ],
    "Legal & Education": [
      "Legal Advisor",
      "Attorney/Lawyer",
      "Prosecutor",
      "Judge",
      "Legal Researcher",
      "Contract Administrator",
      "Compliance Officer",
      "University Lecturer",
      "High School Teacher",
      "Elementary School Teacher",
      "Kindergarten Teacher",
      "Special Needs Educator",
      "Curriculum Developer",
      "Tutor",
      "School Principal"
    ],
    "Agriculture & Environment": [
      "Agronomist",
      "Animal Science Specialist",
      "Veterinary Doctor",
      "Horticulturist",
      "Soil Scientist",
      "Forestry Expert",
      "Environmental Impact Analyst",
      "Climate Change Researcher",
      "Irrigation Engineer",
      "Agro-Business Manager"
    ],
    "Transportation & Technical Crafts": [
      "Light Vehicle Driver",
      "Heavy Truck Driver",
      "Public Transport Driver (Bus)",
      "Motorcycle Rider/Delivery",
      "Auto Mechanic",
      "Auto Electrician",
      "Electrician (Building)",
      "Plumber",
      "Welder",
      "Mason",
      "Carpenter",
      "Painter",
      "Aluminium Work Specialist",
      "Chef/Cook",
      "Waiter/Waitress",
      "Housekeeping/Janitor",
      "Security Guard"
    ],
    "General & Soft Skills": [
      "Fluent in English (Speaking/Writing)",
      "Amharic Typing & Report Writing",
      "Advanced Microsoft Excel",
      "Data Entry Speed",
      "Critical Thinking",
      "Leadership & Mentorship",
      "Public Speaking",
      "Negotiation",
      "Interpersonal Communication",
      "Conflict Management",
      "Time Management",
      "Self-Motivation",
      "Team Collaboration",
      "Emotional Intelligence",
      "Adaptive Learning",
      "Multi-tasking Ability"
    ]
  };
  static const Map<String, List<String>> categorizedFieldsOfStudy = {
    "Engineering & Technology": [
      "Computer Science",
      "Software Engineering",
      "Information Technology",
      "Civil Engineering",
      "Electrical Engineering",
      "Mechanical Engineering",
      "Chemical Engineering",
      "Architecture"
    ],
    "Business & Economics": [
      "Accounting & Finance",
      "Business Management",
      "Economics",
      "Marketing Management",
      "Logistics & Supply Chain",
      "Banking & Insurance"
    ],
    "Healthcare & Medicine": [
      "Medicine (MD)",
      "Nursing",
      "Public Health",
      "Pharmacy",
      "Medical Laboratory Science",
      "Dental Medicine"
    ],
    "Social Sciences & Law": [
      "Law (LLB)",
      "Psychology",
      "Sociology",
      "Political Science",
      "Journalism & Communication",
      "Social Work"
    ],
    "Natural Sciences": [
      "Biology",
      "Chemistry",
      "Physics",
      "Mathematics",
      "Statistics",
      "Geology"
    ],
    "Agriculture & Environment": [
      "Plant Science",
      "Animal Science",
      "Agricultural Economics",
      "Environmental Science"
    ],
    "Vocational": ["Teaching (Pedagogy)", "Hotel Management", "Fine Arts"]
  };

  // ሁሉንም ዘርፎች በአንድ ዝርዝር (Flat List) ለማግኘት ከፈለግክ
  static List<String> get allFieldsOfStudy {
    return categorizedFieldsOfStudy.values
        .expand((element) => element)
        .toList();
  }

  // የዲግሪ ደረጃዎች
  static const List<String> degreeLevels = [
    "No Formal Education",
    "Grade 1-8",
    "Grade 9-10",
    "Grade 11-12",
    "Certificate",
    "TVET / Level 1-4",
    "Diploma",
    "Higher Diploma",
    "Associate Degree",
    "Bachelor's Degree",
    "BSc Degree",
    "BA Degree",
    "Bachelor's of Science",
    "Bachelor's of Arts",
    "Bachelor's Degree (Honors)",
    "Bachelor's Degree (Pass)",
    "Bachelor's Degree (General)",
    "Bachelor's of Science Degree",
    "Bachelor's of Arts Degree",
    "Bachelor's Degree (BBA)",
    "MAster's Degree (MSc)",
    "MAster's Degree (MA)",
    "Master's Degree (MBA)",
    "Master's Degree (MEd)",
    "Master's Degree (MPhil)",
    "Master's Degree (LLM)",
    "PhD",
    "Doctor of Medicine (MD)",
    "Doctor of Philosophy",
    "Doctor of Science",
    "Doctorate",
    "Postdoctoral Research"
  ];

  static const List<String> commonLanguages = [
    "Afaan Oromoo",
    "Afar",
    "Afrikaans",
    "Agaw",
    "Albanian",
    "Amharic",
    "Arabic",
    "Armenian",
    "Azerbaijani",
    "Basque",
    "Belarusian",
    "Bengali",
    "Bosnian",
    "Bulgarian",
    "Catalan",
    "Chinese",
    "Croatian",
    "Czech",
    "Danish",
    "Dutch",
    "English",
    "Estonian",
    "Finnish",
    "French",
    "Gamo",
    "Gedeo",
    "Georgian",
    "German",
    "Greek",
    "Gujarati",
    "Gurage",
    "Hadiya",
    "Hausa",
    "Hebrew",
    "Hindi",
    "Hungarian",
    "Icelandic",
    "Igbo",
    "Indonesian",
    "Irish",
    "Italian",
    "Japanese",
    "Javanese",
    "Kafa",
    "Kannada",
    "Kazakh",
    "Khmer",
    "Korean",
    "Lao",
    "Latin",
    "Latvian",
    "Lithuanian",
    "Luxembourgish",
    "Macedonian",
    "Malagasy",
    "Malay",
    "Malayalam",
    "Maltese",
    "Maori",
    "Marathi",
    "Mongolian",
    "Nepali",
    "Norwegian",
    "Pashto",
    "Persian",
    "Polish",
    "Portuguese",
    "Punjabi",
    "Romanian",
    "Russian",
    "Sanskrit",
    "Serbian",
    "Sidamo",
    "Silte",
    "Sindhi",
    "Sinhala",
    "Slovak",
    "Slovenian",
    "Somali",
    "Spanish",
    "Sudanese",
    "Swahili",
    "Swedish",
    "Tagalog",
    "Tajik",
    "Tamil",
    "Telugu",
    "Thai",
    "Tigrinya",
    "Turkish",
    "Ukrainian",
    "Urdu",
    "Uzbek",
    "Vietnamese",
    "Welsh",
    "Wolaytta",
    "Xhosa",
    "Yiddish",
    "Yoruba",
    "Zulu"
  ];

  // ለቋንቋ ብቃት ደረጃዎች (iOS Style Segmented Control ላይ የምንጠቀማቸው)
  static const List<String> languageLevels = [
    "Beginner",
    "Intermediate",
    "Advanced",
    "Fluent",
    "Native"
  ];
}
