name: Flutter Build APK

on:
  push:
    branches:
      - main 

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: '17'

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: 'stable'

      - name: Create Config File
        run: |
          echo '{
            "GEMINI_KEY": "${{ secrets.GEMINI_KEY }}",
            "GROQ_KEY": "${{ secrets.GROQ_KEY }}",
            "HF_KEY": "${{ secrets.HF_KEY }}",
            "OPENAI_KEY": "${{ secrets.OPENAI_KEY }}",
            "GOOGLE_CLIENT_ID": "${{ secrets.GOOGLE_CLIENT_ID }}",
            "SUPABASE_URL": "${{ secrets.SUPABASE_URL }}",
            "SUPABASE_ANON_KEY": "${{ secrets.SUPABASE_ANON_KEY }}"
          }' > config.json

      - name: Get dependencies
        run: flutter pub get

      - name: Build APK
        run: |
          flutter build apk --release --split-per-abi --obfuscate \
          --split-debug-info=build/app/outputs/symbols \
          --dart-define-from-file=config.json

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: CV-Maker-Pro-APKs
          path: build/app/outputs/flutter-apk/*.apk
