name: Flutter Build APK

on:
  push:
    branches:
      - main 

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: '17'

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: 'stable'

      - name: Get dependencies
        run: flutter pub get

      - name: Build APK
        run: flutter build apk --release --split-per-abi --obfuscate --split-debug-info=build/app/outputs/symbols --dart-define=GEMINI_KEY=${{ secrets.GEMINI_KEY }} --dart-define=GROQ_KEY=${{ secrets.GROQ_KEY }} --dart-define=HF_KEY=${{ secrets.HF_KEY }} --dart-define=OPENAI_KEY=${{ secrets.OPENAI_KEY }} --dart-define=GOOGLE_CLIENT_ID=${{ secrets.GOOGLE_CLIENT_ID }} --dart-define=SUPABASE_URL=${{ secrets.SUPABASE_URL }} --dart-define=SUPABASE_ANON_KEY=${{ secrets.SUPABASE_ANON_KEY }}

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: CV-Maker-Pro-APKs
          path: build/app/outputs/flutter-apk/*.apk
